# Custom Language File for Launcher Customizer

[ejs.app]
title = "Aurora Vitae Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/alio13013"
mediaTwitterURL = "https://x.com/auroravitaesmp"
mediaInstagramURL = "https://www.tiktok.com/@avsmp"
mediaYouTubeURL = "https://youtube.com/@auroravitaesmp"
mediaDiscordURL = "https://discord.gg/avsmp"

[ejs.settings]
sourceGithubLink = "https://github.com/alio13013"
supportLink = "https://discord.gg/avsmp"
selectLanguage = "Select a Language"
changeLanguageTitle = "Change the launcher language"
changeLanguageDesc = "You can change the language in the list below. This text will not change if you change the language so you can find your wayback here to change it back"

[ejs.welcome]
welcomeHeader = "WELCOME TO Aurora Vitae SMP"
welcomeDescription = """
Welcome to Aurora Vitae SMP, where your Minecraft adventure begins! Immerse yourself in a world of endless possibilities and unforgettable experiences on the best SMP server you can imagine. Join our vibrant community of players and embark on epic quests, build amazing creations, and forge lasting friendships.

But wait, there's more! To join in the fun, just hop onto our Discord server to self-register and gain access to our exclusive realm of emotions. Whether you're a seasoned explorer or a novice builder, ZSMP welcomes players of all skill levels.

So, what are you waiting for? Click "Continue" and let the adventures begin!
"""

[ejs.overlay]
changedLanguageHeader = "You changed the previous language"