# Custom Language File for Launcher Customizer

[ejs.app]
title = "Aurora Vitae Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/alio13013"
mediaTwitterURL = "https://x.com/auroravitaesmp"
mediaInstagramURL = "https://www.tiktok.com/@avsmp"
mediaYouTubeURL = "https://youtube.com/@auroravitaesmp"
mediaDiscordURL = "https://discord.gg/avsmp"

[ejs.settings]
sourceGithubLink = "https://github.com/alio13013"
supportLink = "https://discord.gg/avsmp"
selectLanguage = "Select a Language"
changeLanguageTitle = "Change the launcher language"
changeLanguageDesc = "You can change the language in the list below. This text will not change if you change the language so you can find your wayback here to change it back"

[ejs.welcome]
welcomeHeader = "Bem Vindo ao Aurora Vitae SMP"
welcomeDescription = """
Bem-vindo ao Aurora Vitae SMP — onde o silêncio do Exílio guarda ecos de novos destinos.
Junte-se a almas errantes que, como você, foram despertadas por algo maior. — para construir, lembrar, lutar e imaginar. Em meio às muralhas do Exílio, surgem pontes, histórias e laços forjados em esperança e desafios.

Mas espere, tem mais! Para participar da diversão, basta acessar nosso servidor do Discord para se cadastrar e ter acesso ao nosso reino exclusivo de emoções. Seja você um explorador experiente ou um construtor iniciante, o AVSMP acolhe jogadores de todos os níveis.

Então, o que você está esperando? Clique em "Continuar" e desperte em suas novas aventuras!
"""

[ejs.overlay]
changedLanguageHeader = "You changed the previous language"